# Generated by Django 2.1 on 2019-04-14 12:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Shirts', 'Shirts'), ('Custiomised_Vest', 'Custiomised Vest'), ('Native_Wears', 'Native_Wears'), ('Footwears', 'Footwears'), ('Trousers', 'Trousers'), ('Caps', 'Caps')], max_length=60, null=True),
        ),
    ]
