# Generated by Django 2.1 on 2019-04-14 16:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190414_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Shirts', 'Shirts'), ('Custiomisedvest', 'Custiomised Vest'), ('Nativewears', 'Native Wears'), ('Footwears', 'Footwears'), ('Trousers', 'Trousers'), ('Caps', 'Caps')], max_length=58, null=True),
        ),
    ]
