# Generated by Django 2.1 on 2019-04-14 16:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190414_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Shirts', 'Shirts'), ('Custiomised vest', 'Custiomised Vest'), ('Native wears', 'Native Wears'), ('Footwears', 'Footwears'), ('Trousers', 'Trousers'), ('Caps', 'Caps')], max_length=60, null=True),
        ),
    ]
